### ISSUE TITLE
td-agent-gem install fails for fluent-plugin-elasticsearch

### ISSUE THREAD

**Issue by kiyoto** [treasure-data/omnibus-td-agent#16]
```shell
/usr/sbin/td-agent-gem install fluent-plugin-elasticsearch

Fetching: patron-0.4.18.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-elasticsearch:
	ERROR: Failed to build gem native extension.

        /opt/td-agent/embedded/bin/ruby extconf.rb
checking for curl-config... yes
checking for rb_thread_blocking_region()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/td-agent/embedded/bin/ruby
	--with-curl-dir
	--without-curl-dir
	--with-curl-include
	--without-curl-include=${curl-dir}/include
	--with-curl-lib
	--without-curl-lib=${curl-dir}/lib
/opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1027:in `block in have_func'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
	from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1026:in `have_func'
	from extconf.rb:47:in `<main>'


Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/patron-0.4.18 for inspection.
Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/patron-0.4.18/ext/patron/gem_make.out
```

I believe this happens with any gem that requires a native extension?

**Comment by jypkor** [comment]
I fixed issue.
install libcurl-devel & gcc

**Comment by kiyoto** [comment]
@jypkor I believe your situation is different from @mumhero since @mumhero already has libcurl-devel & make (otherwise, he shouldn't be able to install with `gem install fluent-plugin-elasticsearch`)

**Comment by kiyoto** [comment]
@repeatedly let me know what your thought is. On Centos7, installing libcurl-devel+gcc still does not work:

```
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-elasticsearch:
        ERROR: Failed to build gem native extension.

    /opt/td-agent/embedded/bin/ruby extconf.rb
checking for curl-config... yes
checking for rb_thread_blocking_region()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/td-agent/embedded/bin/ruby
        --with-curl-dir
        --without-curl-dir
        --with-curl-include
        --without-curl-include=${curl-dir}/include
        --with-curl-lib
        --without-curl-lib=${curl-dir}/lib
/opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1027:in `block in have_func'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1026:in `have_func'
        from extconf.rb:47:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/patron-0.4.18 for inspection.
Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/patron-0.4.18/gem_make.out
```

**Comment by repeatedly** [comment]
I uploaded td-agent 2.1.3-1 for this issue.
Could you try this version?

**Comment by repeatedly** [comment]
> I have exactly the same problem, td-agent 2.1.3-0 on debian wheezy. 

Hmm... Debian wheezy is different from Ubuntu distributions?
fluent-plugin-elasticsearch installation is succeeded on Ubuntu.

**Comment by repeatedly** [comment]
Can we close this issue?

**Comment by darkwise** [comment]
On Debian 7 (wheezy), **libcurl4-gnutls-dev** works fine, libcurl4-openssl-dev failed.

**Comment by repeatedly** [comment]
@darkwise Interesting. I'm not sure what the different between libcurl4-gnutls-dev and libcurl4-openssl-dev...
But latest fluent-plugin-elasticsearch doesn't need libcurl dependency so this problem should be resolved.

**Comment by vhosakot** [comment]
`yum install gcc gcc-c++ ruby-devel` resolved this error in CentOS for me.

**Comment by AjeetK** [comment]
You need to install `build-essential` as well if you are on ubuntu-16.04. I got it working by following setup instruction on [Appychip](https://jee-appy.blogspot.in/2018/02/setup-efk-stack-elasticsearch-fluentd.html)

```
sudo apt-get install make libcurl4-gnutls-dev --yes
sudo apt-get install build-essential
```

**Comment by prashantp48** [comment]
Thanks @AjeetK , it worked flawlessly.

**Comment by fil-monterey** [comment]
Installing gcc and libcurl-devel packages resolved this.
yum install libcurl-devel gcc

then was able to successfully install the gem:
/opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-splunk-http-eventcollector
